# Generated by Django 5.0.4 on 2024-04-05 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_name"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Posts",
            new_name="Post",
        ),
    ]
